version: 0.{build}

branches:
  except:
    - gh-pages
    - docs

image: macos-monterey

clone_depth: 3

environment:
  GITHUB_NAME: mandeuk26
  
install:
  - xcodebuild -version
  
configuration:
  - Debug

before_build:
  - env
  
build_script:
  - echo "hello"
